### ISSUE TITLE
/var/lib/jenkins folder empty

### ISSUE THREAD

**Issue by AmitPhulera** [awslabs/aws-cicd-docker-containers#1]
Hi,
I am new to AWS and was trying to implement CI/CD pipeline in AWS. I got stuck on  Step 2 => 4nd Point.
In EC2 instance /var/lib/jenkins was empty and curl to localhost:8080 gives :- 
HTTP ERROR: 503
Problem accessing /. Reason:
Service Unavailable

I am unable to figure out the reason why it is happening.
Thanks .

**Comment by jicowan** [comment]
Hi Amit, 
Sorry you're having trouble.  Sounds like Jenkins wasn't.  I'll try running through this again later this week.  Meanwhile, try running the CFN stack template for Jenkins again.
The formatting for the README is all messed up.  Not sure it contributed to this problem, but I need to fix that too.

**Comment by AmitPhulera** [comment]
Thankyou Jeremy,
The issue was solved by reinstalling Jenkins.
I have tried running the template 4 times but each time I got same result.

**Comment by jicowan** [comment]
Hi Amit, 
I fixed the CFN template so that it installs Java 1.8.0.  It should work now.  This getting started guide was published on http://docs.aws.amazon.com/AWSGettingStartedContinuousDeliveryPipeline/latest/GettingStarted/CICD_Jenkins_Pipeline.html.  The formatting is fixed on that site.
