### ISSUE TITLE
Jenkins directory empty

### ISSUE THREAD

**Issue by nvashish123** [awslabs/aws-cicd-docker-containers#2]
Like the previous comment, somehow the Jenkins directory is empty and I am not able to proceed with the setup. I tried to run the commands manually on my EC2 instances, but I still dont see my Jenkins page show up. 
Are you planning to fix this issue and update this page? Thanks!

**Comment by jicowan** [comment]
Thanks for bringing this to my attention.  I have to update the CFN template for Jenkins.  The latest version of Jenkins no longer supports the version of Java that is on the AMI.  If you don't want to wait for me to update the CFN template, you can install the version 1.8.0 of Java by running `sudo yum install -y java-1.8.0` and then uninstalling 1.7.0 by running `sudo yum remove java-1.7.0-openjdk` and then start Jenkins by running `sudo service jenkins start`.
