### ISSUE TITLE
folder /var/lib/jenkins doesn't exist

### ISSUE THREAD

**Issue by kdcc** [awslabs/aws-cicd-docker-containers#4]
Hi, I'm trying this guide, but I can't find /var/lib/jenkins when come to step 2.4(SSH into the instance, and then copy the temp password...).

Looking forward someone's help, thanks a lot!

**Comment by tsamaya** [comment]
Just trying the template now.

The stack has indeed a CREATE_COMPLETE status but Jenkins is not installed 

UserData script is not properly exectuted:
https://github.com/jicowan/hello-world/blob/master/ecs-jenkins-demo.template#L433

I executed the commands one by one to get to the next step

**Comment by jicowan** [comment]
Having a look...

**Comment by jicowan** [comment]
I need to update the AMI ID in the template.  Doing that now.

**Comment by jicowan** [comment]
Updated AMI mappings in CFN template for Jenkins https://github.com/jicowan/hello-world/blob/master/ecs-jenkins-demo.template#L433.
